# Generated by Django 5.0.6 on 2024-07-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
